---
#
# Provisions all the required dependencies for Wistar on the remote host
#

- name: "Install Python"
  raw: "apt-get update && apt-get install -y python"

- name: "Gather facts"
  setup:

- name: "Install Wistar dependencies with apt"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - qemu-kvm
    - libvirt-bin
    - libvirt-dev
    - socat
    - unzip
    - bridge-utils
    - genisoimage
    - mtools
    - dosfstools
    - pkg-config
    - libvirt-bin

- name: "Install python-pip with apt"
  apt:
    name: python-pip
    state: present

- name: "Update Python pip to latest version"
  pip:
    name: pip
    state: latest

- name: "Install Wistar python dependencies with pip"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - numpy
    - cryptography
    - junos-eznc
    - jxmlease
    - django==1.9.9
    - pyvbox
    - markupsafe
    - netaddr
    - pyyaml
    #https://bugs.launchpad.net/openstack-requirements/+bug/1753539
    - libvirt-python==4.0.0
    - pexpect

- name: "Create Wistar directory structure 1"
  file:
    path: /opt/wistar
    state: directory

- name: "Create Wistar directory structure 2"
  file:
    path: /opt/wistar/user_images
    state: directory

- name: "Create Wistar directory structure 3"
  file:
    path: /opt/wistar/wistar-master
    state: directory

- name: "Create Wistar directory structure 4"
  file:
    path: /opt/wistar/media
    state: directory

- name: "Create Wistar directory structure 5"
  file:
    path: /opt/wistar/seeds
    state: directory

- name: "Create Wistar directory structure 6"
  file:
    path: /opt/wistar/user_images/instances
    state: directory

- name: "Pull Wistar branch <{{ wistar_git_branch }}> from github"
  git:
    repo: https://github.com/Juniper/wistar.git
    dest: /opt/wistar/wistar-master/
    version: "{{ wistar_git_branch }}"

- name: "Create Wistar tables"
  command: /opt/wistar/wistar-master/manage.py migrate

- name: "Set permissions on Wistar log"
  file:
    path: /var/log/wistar.log
    state: touch

- name: "Copy Wistar configuration.py"
  template:
    src: templates/configuration.j2
    dest: /opt/wistar/wistar-master/wistar/configuration.py

- name: "Create Wistar service"
  template:
    src: templates/wistar_unit.j2
    dest: /etc/systemd/system/wistar.service

- name: "Start Wistar service"
  service:
    name: wistar
    state: started
    enabled: yes